#include <iostream>
#include <vector>
#include "levels.h"

Levels::Levels()
{

	level[0]={	  "XXXXXXXXXX",
				  "X        X",
				  "X   *XXX X",
				  "XX  @    X",
				  "XX XXX X X",
				  "XX * * X.X",
				  "X    X X.X",
				  "X   X  X.X",
				  "X        X",
				  "XXXXXXXXXX"};
	level[1]={	"    XXXXX             ",
				"    X   X             ",
				"    X*  X             ",
				"  XXX  *XXX           ",
				"  X  *  * X           ",
				"XXX X XXX X     XXXXXX",
				"X   X XXX XXXXXXX  ..X",
				"X *  *             ..X",
				"XXXXX XXXX X@XXXX  ..X",
				"    X      XXX  XXXXXX",
				"    XXXXXXXX          "};

	level[2] = {"XXXXXXXXXXXX  ",
				"X..  X     XXX",
				"X..  X *  *  X",
				"X..  X*XXXX  X",
				"X..    @ XX  X",
				"X..  X X  * XX",
				"XXXXXX XX* * X",
				"  X *  * * * X",
				"  X    X     X",
				"  XXXXXXXXXXXX"};

	level[3]={"        XXXXXXXX",
			  "        X     @X",
			  "        X *X* XX",
			  "        X *  *X ",
			  "        XX* * X ",
			  "XXXXXXXXX * X XXX",
			  "X....  XX *  *  X",
			  "XX...    *  *   X",
			  "X....  XXXXXXXXXX",
			  "XXXXXXXX         "};
	level[4]= {"              XXXXXXXX",
			   "              X  ....X",
			   "   XXXXXXXXXXXX  ....X",
			   "   X    X  * *   ....X",
			   "   X ***X*  * X  ....X",
			   "   X  *     * X  ....X",
			   "   X ** X* * *XXXXXXXX",
			   "XXXX  * X     X       ",
			   "X   X XXXXXXXXX       ",
			   "X    *  XX            ",
			   "X **X** @X            ",
			   "X   X   XX            ",
			   "XXXXXXXXX             "};
	level[5]={"        XXXXX    ",
			  "        X   XXXXX",
			  "        X X*XX  X",
			  "        X     * X",
			  "XXXXXXXXX XXX   X",
			  "X....  XX *  *XXX",
			  "X....    * ** XX ",
			  "X....  XX*  * @X ",
			  "XXXXXXXXX  *  XX ",
			  "        X * *  X ",
			  "        XXX XX X ",
			  "          X    X ",
			  "          XXXXXX "};
	level[6]={"XXXXXX  XXX ",
			  "X..  X XX@XX",
			  "X..  XXX   X",
			  "X..     ** X",
			  "X..  X X * X",
			  "X..XXX X * X",
			  "XXXX * X*  X",
			  "   X  *X * X",
			  "   X *  *  X",
			  "   X  XX   X",
			  "   XXXXXXXXX"};
	level[7]={"       XXXXX ",
			  " XXXXXXX   XX",
			  "XX X @XX ** X",
			  "X    *      X",
			  "X  *  XXX   X",
			  "XXX XXXXX*XXX",
			  "X *  XXX ..X ",
			  "X * * * ...X ",
			  "X    XXX...X ",
			  "X ** X X...X ",
			  "X  XXX XXXXX ",
			  "XXXX         "};
	level[8]={"  XXXX          ",
			  "  X  XXXXXXXXXXX",
			  "  X    *   * * X",
			  "  X *X * X  *  X",
			  "  X  * *  X    X",
			  "XXX *X X  XXXX X",
			  "X@X* * *  XX   X",
			  "X    * X*X   X X",
			  "XX  *    * * * X",
			  " XXXX  XXXXXXXXX",
			  "  XXX  XXX      ",
			  "  X      X      ",
			  "  X      X      ",
			  "  X......X      ",
			  "  X......X      ",
			  "  X......X      ",
			  "  XXXXXXXX      "};
	level[9]={"          XXXXXXX",
			  "          X  ...X",
			  "      XXXXX  ...X",
			  "      X      ...X",
			  "      X  XX  ...X",
			  "      XX XX  ...X",
			  "     XXX XXXXXXXX",
			  "     X *** XX    ",
			  " XXXXX  * * XXXXX",
			  "XX   X* *   X   X",
			  "X@ *  *    *  * X",
			  "XXXXXX ** * XXXXX",
			  "     X *    X    ",
			  "     XXXX XXX    ",
			  "        X  X     ",
			  "        X  X     ",
			  "        X  X     ",
			  "        XXXX     "};
	level[10]={"              XXXX   ",
			   "         XXXXXX  X   ",
			   "         X       X   ",
			   "         X  XXXX XXX ",
			   " XXX  XXXXX XXX    X ",
			   "XX@XXXX   *** X    X ",
			   "X **   ** *   X....XX",
			   "X  ***X    *  X.....X",
			   "X *   X ** ** X.....X",
			   "XXX   X  *    X.....X",
			   "  X   X * * * X.....X",
			   "  X XXXXXXX XXX.....X",
			   "  X   X  * *  X.....X",
			   "  XXX X ** * *XXXXXXX",
			   "    X X  *      X    ",
			   "    X X *** *** X    ",
			   "    X X       X X    ",
			   "    X XXXXXXXXX X    ",
			   "    X           X    ",
			   "    XXXXXXXXXXXXX    "};
	level[11]={"          XXXX     ",
			   "     XXXX X  X     ",
			   "   XXX  XXX* X     ",
			   "  XX   @  *  X     ",
			   " XX  * **XX XX     ",
			   " X  X*XX     X     ",
			   " X X * ** X XXX    ",
			   " X   * X  X * XXXXX",
			   "XXXX    X  ** X   X",
			   "XXXX XX *         X",
			   "X.    XXX  XXXXXXXX",
			   "X.. ..X XXXX       ",
			   "X...X.X            ",
			   "X.....X            ",
			   "XXXXXXX            "};
	level[12]={"  XXXXXXXXX  ",
			   "  X&.&X&.&X  ",
			   "  X.&.&.&.X  ",
			   "  X&.&.&.&X  ",
			   "  X.&.&.&.X  ",
			   "  X&.&.&.&X  ",
			   "  XXX   XXX  ",
			   "    X   X    ",
			   "XXXXXX XXXXXX",
			   "X           X",
			   "X * * * * * X",
			   "XX * * * * XX",
			   " X* * * * *X ",
			   " X   *@*   X ",
			   " X  XXXXX  X ",
			   " XXXX   XXXX "};
	level[13]={"    XXXXXXXXX       ",
			   "  XXX   XX  XXXXX   ",
			   "XXX      X  X   XXXX",
			   "X  ** X* X  X  ... X",
			   "X X  *X@*XX X X.X. X",
			   "X  XX X*  X    ... X",
			   "X *X    * X X X.X. X",
			   "X    XX  XX* * ... X",
			   "X * XX   X  X*X.X. X",
			   "XX **  *   *  *... X",
			   " X*  XXXXXX    XX  X",
			   " X   X    XXXXXXXXXX",
			   " XXXXX              "};
	level[14]={"XXXXXXXXXXXXXXXX ",
			   "X              X ",
			   "X X XXXXXX     X ",
			   "X X  * * * *X  X ",
			   "X X   *@*   XX XX",
			   "X X X* * *XXX...X",
			   "X X   * *  XX...X",
			   "X XXX*** * XX...X",
			   "X     X XX XX...X",
			   "XXXXX   XX XX...X",
			   "    XXXXX     XXX",
			   "        X     X  ",
			   "        XXXXXXX  "};
	level[15]={"       XXXX      ",
			   "    XXXX  X      ",
			   "   XX  X  X      ",
			   "   X  * * X      ",
			   " XXX X*   XXXX   ",
			   " X  *  XX*   X   ",
			   " X  X @ * X *X   ",
			   " X  X      * XXXX",
			   " XX XXXX*XX     X",
			   " X *X.....X X   X",
			   " X  *...&. *X XXX",
			   "XX  X.....X   X  ",
			   "X   XXX XXXXXXX  ",
			   "X **  X  X       ",
			   "X  X     X       ",
			   "XXXXXX   X       ",
			   "     XXXXX       "};
	level[16]={"XXXXX         ",
			   "X   XX        ",
			   "X    X  XXXX  ",
			   "X *  XXXX  X  ",
			   "X  ** *   *X  ",
			   "XXX@ X*    XX ",
			   " X  XX  * * XX",
			   " X *  XX XX .X",
			   " X  X*XX*  X.X",
			   " XXX   *..XX.X",
			   "  X    X.&...X",
			   "  X ** X.....X",
			   "  X  XXXXXXXXX",
			   "  X  X        ",
			   "  XXXX        "};
	level[17]={"       XXXXXXX    ",
			   " XXXXXXX     X    ",
			   " X     X *@* X    ",
			   " X** X   XXXXXXXXX",
			   " X XXX......XX   X",
			   " X   *......XX X X",
			   " X XXX......     X",
			   "XX   XXXX XXX X*XX",
			   "X  X*   X  *  X X ",
			   "X  * ***  X *XX X ",
			   "X   * * XXX** X X ",
			   "XXXXX     *   X X ",
			   "    XXX XXX   X X ",
			   "      X     X   X ",
			   "      XXXXXXXX  X ",
			   "             XXXX "};
	level[18]={"      XXXXXXXXXXXX    ",
			   "      X  .  XX   X    ",
			   "      X X.     @ X    ",
			   " XXXXXX XX...X XXXX   ",
			   "XX  XX...XXXX     XXXX",
			   "X * XX...    * X  *  X",
			   "X     .. XX X XX XX  X",
			   "XXXX*XXX*X *  X   X XX",
			   " XXX  X    XX* ** X X ",
			   " X   ** X X * X *XX X ",
			   " X                  X ",
			   " XXXXXXXXXXXXXXXXX  X ",
			   "                 XXXX "};
	level[19]={"        XXXXXX              ",
			   "        X   @XXXX           ",
			   "      XXXXX *   X           ",
			   "      X   XX    XXXX        ",
			   "      X *XX  XX    X        ",
			   "      X   X  XXXXX X        ",
			   "      X X** *    X X        ",
			   "      X  * * XXX X X        ",
			   "      X X   *  X X X        ",
			   "      X X  X*X   X X        ",
			   "     XX XXXX   X X X        ",
			   "     X  *  XXXXX X X XXXX   ",
			   "    XX    *     *  XXX  XXXX",
			   "XXXXX  XXX * *X * X   .....X",
			   "X     XX      X  XX  X.....X",
			   "X ****    XXXXXX*XX   X.XX.X",
			   "XX    XX              X....X",
			   " XX  XXXXXXXXXXXXXXX   ....X",
			   "  X  X             XXXXX  XX",
			   "  XXXX                 XXXX "};
	level[20]={"       XXXXXXXXXXXX ",
			   "       X..........X ",
			   "     XXX.X.X.X.X..X ",
			   "     X   .........X ",
			   "     X@ * * * &.&.X ",
			   "    XXXXXXX XXXXXXX ",
			   " XXXX   X    XX  X  ",
			   "XX    * X    X * XX ",
			   "X  X*X XXX XXX*   XX",
			   "X *  * *   X * * * X",
			   "X  X * XX       X* X",
			   "X   *XXXX*XXXX*XX  X",
			   "XXXX  XX   X    X  X",
			   "   X* XX   X X **  X",
			   "   X   X * X  *    X",
			   "   XXX X ** X  * XXX",
			   "     X X    X * XX  ",
			   "     X XXXXXXXX X   ",
			   "     X          X   ",
			   "     XXXXXXXXXXXX   "};
	level[21]={"   XXXXXXXXXX   ",
			   "   X..  X   X   ",
			   "   X..      X   ",
			   "   X..  X  XXXX ",
			   "  XXXXXXX  X  XX",
			   "  X            X",
			   "  X  X  XX  X  X",
			   "XXXX XX  XXXX XX",
			   "X  *  XXXXX X  X",
			   "X X *  *  X *  X",
			   "X @*  *   X   XX",
			   "XXXX XX XXXXXXX ",
			   "   X    X       ",
			   "   XXXXXX       "};
	level[22]={"            XXXX      ",
			   " XXXXXXXXXXXX  XXXXX  ",
			   " X    X  X  *  X   XX ",
			   " X * * *  * X * *   X ",
			   " XX* *   X @X *   * X ",
			   "XXX   XXXXXXXXXXXX XX ",
			   "X  * *X  X......X *X  ",
			   "X X   X  X......XX X  ",
			   "X  XX XX X .....X  X  ",
			   "X X      *...... * X  ",
			   "X X * XX X......X  X  ",
			   "X  * *X  X......X *X  ",
			   "X *   X  XX*XXXXX  X  ",
			   "X * * XXXX * *  * *X  ",
			   "XX X     * * * *   XXX",
			   " X  XXXXXX *    *    X",
			   " X         X XXXXXXX X",
			   " XXXXXXX X*          X",
			   "       X   XXXXXXXXXXX",
			   "       XXXXX          "};
	level[23]={"       XXXXXXX           ",
			   "       X  X  XXXX        ",
			   "       X *X* X  XX       ",
			   "XXXXXXXX  X  X   XXXXXXXX",
			   "X....  X *X* X  *X  X   X",
			   "X....X X     X*  X      X",
			   "X..X.    *X  X *    X*  X",
			   "X... @XX  X* X*  X  X   X",
			   "X.... XX *X     *XXXXXXXX",
			   "XXXXXXXX  X**X*  X       ",
			   "       X *X  X  *X       ",
			   "       X  X  X   X       ",
			   "       XXXX  XXXXX       ",
			   "          XXXX           "};
	level[24]={"   XXXXXXXXXX        ",
			   "   X........XXXX     ",
			   "   X.X.X....X  X     ",
			   "   X........** X     ",
			   "   X     .XXX  XXXX  ",
			   " XXXXXXXXX  * X   X  ",
			   " X     *   * *  * X  ",
			   " X  X    X  * *X  X  ",
			   " XX XXXXX   X  X  X  ",
			   " X *     X   XXXX X  ",
			   "XX  *X   X XX  X  X  ",
			   "X    XX*XXX    X  XX ",
			   "X *    * X  X  X   X ",
			   "XXXXX    X XX X XX XX",
			   "    X*X X  *  * *   X",
			   "    X@X  *X***  X   X",
			   "    XXX  *      XXXXX",
			   "      XX  X  X  X    ",
			   "       XXXXXXXXXX    "};
	level[25]={"               XXXX    ",
			   "          XXXXXX  XXXXX",
			   "    XXXXXXX       X   X",
			   "    X      * * XX X X X",
			   "    X  XXXX *  X     .X",
			   "    X      * X X XX.X.X",
			   "    XX*XXXX* * * XX.X.X",
			   "    X     X    XXXX.XXX",
			   "    X *   XXXXXX  X.X.X",
			   "XXXXXX***XX      @X.X.X",
			   "X      X    X*X*XXX. .X",
			   "X XXXX X*****    X ...X",
			   "X X    *     X   X ...X",
			   "X X   XX XX     XXX...X",
			   "X XXXXXX*XXXXXX  XXXXXX",
			   "X        X    X  X     ",
			   "XXXXXXXXXX    XXXX     "};
	level[26]={"XXXXXXXXX      ",
			   "X       X      ",
			   "X       XXXX   ",
			   "XX XXXX X  X   ",
			   "XX X@XX    X   ",
			   "X *** *  **X   ",
			   "X  X XX *  X   ",
			   "X  X XX  * XXXX",
			   "XXXX  *** *X  X",
			   " X   XX   ....X",
			   " X X   X X.. .X",
			   " X   X X XX...X",
			   " XXXXX *  X...X",
			   "     XX   XXXXX",
			   "      XXXXX    "};
	level[27]={" XXXXXXXXXXXXXXXXX     ",
			   " X...   X    X   XXX   ",
			   "XX.....  *XX X X * X   ",
			   "X......X  *  X  *  X   ",
			   "X......X  X  X X X XX  ",
			   "XXXXXXXXX *  * X X  XXX",
			   "  X     X*XX* XX XX   X",
			   " XX   *    X *  *   X X",
			   " X  XX XXX X  XXXXX*X X",
			   " X * **     *   *     X",
			   " X *    *XX* XXXXXXXX X",
			   " XXXXXXX  @ XX      XXX",
			   "       XXXXXX          "};
	level[28]={"     XXXXXXX   ",
			   "     X@ X  X   ",
			   "     X *   X   ",
			   "    XXX XX X   ",
			   " XXXX *  X XX  ",
			   " X       X  XX ",
			   " X * *XXXX * X ",
			   " X ** X  X  *X ",
			   " X*  *   X*  X ",
			   "XX  **X   ** XX",
			   "X **  X  X  * X",
			   "X     XXXX *  X",
			   "X  X*XX..XX   X",
			   "XXX .X....XXXXX",
			   "  X .......XX  ",
			   "  X....   ..X  ",
			   "  XXXXXXXXXXX  "};
	level[29]={"                XXXXX   ",
			   "       XXXXXX XXX   XXXX",
			   "   XXXXX    XXX * *  * X",
			   "XXXX  XX X* *    * X   X",
			   "X....   ** * *  *   X*XX",
			   "X.. X XX X   XXX*XX X  X",
			   "X....    X XXX    X    X",
			   "X....    X XX  *  XXX* X",
			   "X..XXXXXX  *  X  XXXX XX",
			   "XXXX    X   XXX    @  X ",
			   "        XXXXXXXXXXXXXXX "};
	level[30]={" XXXXX        ",
			   " X   XXXXXXX  ",
			   " X * XXX   X  ",
			   " X *    ** X  ",
			   " XX XXXX   X  ",
			   "XXX X  X XXX  ",
			   "X   X  X@XX   ",
			   "X **    * X   ",
			   "X   X X * XXXX",
			   "XXXXX X   X  X",
			   " X   *XXXX   X",
			   " X  *     *  X",
			   " XX   XXXXX XX",
			   " XXXXXXXXXX  X",
			   "XX....X *  * X",
			   "X.....X **X  X",
			   "X.. ..X *  * X",
			   "X.....*   X  X",
			   "XX  XXXXXXXXXX",
			   " XXXX         "};
	level[31]={" XXXXXXX       ",
			   " X  X  XXXXX   ",
			   "XX  X  X...XXX ",
			   "X  *X  X...  X ",
			   "X * X** ...  X ",
			   "X  *X  X... .X ",
			   "X   X *XXXXXXXX",
			   "XX*       * * X",
			   "XX  X  ** X   X",
			   " XXXXXX  XX**@X",
			   "      X      XX",
			   "      XXXXXXXX "};
	level[32]={"  XXXX            ",
			   "  X  XXXXXXXXX    ",
			   " XX  XX @X   X    ",
			   " X  *X * *   XXXX ",
			   " X*  *  X * *X  XX",
			   "XX  *XX X* *     X",
			   "X  X  X X   ***  X",
			   "X *    *  *XX XXXX",
			   "X * * X*X  X  X   ",
			   "XX  XXX  XXX* X   ",
			   " X  X....     X   ",
			   " XXXX......XXXX   ",
			   "   X....XXXX      ",
			   "   X...XX         ",
			   "   X...X          ",
			   "   XXXXX          "};
	level[33]={"      XXXX   ",
			   "  XXXXX  X   ",
			   " XX     *X   ",
			   "XX *  XX XXX ",
			   "X@* * X *  X ",
			   "XXXX XX   *X ",
			   " X....X* * X ",
			   " X....X   *X ",
			   " X....  ** XX",
			   " X... X *   X",
			   " XXXXXX* *  X",
			   "      X   XXX",
			   "      X* XXX ",
			   "      X  X   ",
			   "      XXXX   "};
	level[34]={"XXXXXXXXXXXX",
			   "XX     XX  X",
			   "XX   *   * X",
			   "XXXX XX ** X",
			   "X   * X    X",
			   "X *** X XXXX",
			   "X   X X * XX",
			   "X  X  X  * X",
			   "X *X *X    X",
			   "X   ..X XXXX",
			   "XXXX.. * X@X",
			   "X.....X *X X",
			   "XX....X  * X",
			   "XXX..XX    X",
			   "XXXXXXXXXXXX"};
	level[35]={"XXXXXXXXXXXX  XXXXXX",
			   "X   X    X@XXXX....X",
			   "X   **X       .....X",
			   "X   X XXX   XX ....X",
			   "XX XX XXX  X   ....X",
			   " X * *     X XX XXXX",
			   " X  * *XX  X       X",
			   "XXXX X  XXXX XX XX X",
			   "X  X X*   XX XX    X",
			   "X *  *  X XX XXXXXXX",
			   "X X * *    X X      ",
			   "X  * XX XX X X      ",
			   "X **     **  X      ",
			   "XX XX XXX *  X      ",
			   " X    X X    X      ",
			   " XXXXXX XXXXXX      "};
	level[36]={"     XXXX         ",
			   "   XXX  XX        ",
			   "XXXX  *  X        ",
			   "X   * *  XXXX     ",
			   "X *   X *   X XXXX",
			   "X  X  X   * X X..X",
			   "XX*X* XXXX*XXXX..X",
			   " X   XXXXX XX ...X",
			   " X*X XX@XX XX  ..X",
			   " X X    *     ...X",
			   " X   XXXX XXX  ..X",
			   " XXX XX X  XX ...X",
			   "  XX* XXXX* XXX..X",
			   "  X   XX    X X..X",
			   " XX **XX  * X XXXX",
			   " X     **** X     ",
			   " X * XXX    X     ",
			   " X   X XXXXXX     ",
			   " XXXXX            "};
	level[37]={"XXXXXXXXXXX          ",
			   "X......   XXXXXXXXX  ",
			   "X......   X  XX   X  ",
			   "X..XXX *    *     X  ",
			   "X... * * X  XXX   X  ",
			   "X...X*XXXXX    X  X  ",
			   "XXX    X   X*  X *XXX",
			   "  X  ** * *  *XX  * X",
			   "  X  *   X*X  XX    X",
			   "  XXX XX X  * XXXXXXX",
			   "   X  * * XX XX      ",
			   "   X    *  *  X      ",
			   "   XX   X X   X      ",
			   "    XXXXX@XXXXX      ",
			   "        XXX          "};
	level[38]={" XXXXXXXXX    ",
			   " X....   XX   ",
			   " X.X.X  * XX  ",
			   "XX....X X @XX ",
			   "X ....X  X  XX",
			   "X     X* XX* X",
			   "XX XXX  *    X",
			   " X*  * * *X  X",
			   " X X  * * XX X",
			   " X  XXX  XX  X",
			   " X    XX XX XX",
			   " X  * X  *  X ",
			   " XXX* *   XXX ",
			   "   X  XXXXX   ",
			   "   XXXX       "};
	level[39]={"              XXX      ",
			   "             XX.XXX    ",
			   "             X....X    ",
			   " XXXXXXXXXXXXX....X    ",
			   "XX   XX     XX....XXXXX",
			   "X  **XX  * @XX....    X",
			   "X      ** *X  ....X   X",
			   "X  * XX ** X X....X  XX",
			   "X  * XX *  X XX XXX  X ",
			   "XX XXXXX XXX         X ",
			   "XX   *  * XXXXX XXX  X ",
			   "X *XXX  X XXXXX X XXXX ",
			   "X   *   X       X      ",
			   "X  * X* * *XXX  X      ",
			   "X ***X *   X XXXX      ",
			   "X    X  ** X           ",
			   "XXXXXX   XXX           ",
			   "     XXXXX             "};
	level[40]={"      XXXX ",
			   "XXXXXXX @X ",
			   "X     *  X ",
			   "X   *XX *X ",
			   "XX*X...X X ",
			   " X *...  X ",
			   " X X. .X XX",
			   " X   X X* X",
			   " X*  *    X",
			   " X  XXXXXXX",
			   " XXXX      "};
	level[41]={"           XXXXX    ",
			   "          XX   XX   ",
			   "         XX     X   ",
			   "        XX  **  X   ",
			   "       XX **  * X   ",
			   "       X *    * X   ",
			   "XXXX   X   ** XXXXX ",
			   "X  XXXXXXXX XX    X ",
			   "X..           ***@X ",
			   "X.X XXXXXXX XX   XX ",
			   "X.X XXXXXXX. X* *XXX",
			   "X........... X   * X",
			   "XXXXXXXXXXXXXX  *  X",
			   "             XX  XXX",
			   "              XXXX  "};
	level[42]={" XXXXXXXX    ",
			   " X@XX   XXXX ",
			   " X *   *   X ",
			   " X  * * ***X ",
			   " X **X X   X ",
			   "XX*    *   X ",
			   "X  *  *****XX",
			   "X *XXXX X   X",
			   "X  *....X   X",
			   "X XX....X** X",
			   "X XX....   XX",
			   "X   ....X  X ",
			   "XX X....X**X ",
			   " X X....X  X ",
			   " X         X ",
			   " XXXX XX*XXX ",
			   "    X    X   ",
			   "    XXXXXX   "};
	level[43]={"    XXXXXXXXXXXX ",
			   "    X          XX",
			   "    X  X X** *  X",
			   "    X* X*X  XX @X",
			   "   XX XX X * X XX",
			   "   X   * X*  X X ",
			   "   X   X *   X X ",
			   "   XX * *   XX X ",
			   "   X  X  XX  * X ",
			   "   X    XX **X X ",
			   "XXXXXX**   X   X ",
			   "X....X  XXXXXXXX ",
			   "X.X... XX        ",
			   "X....   X        ",
			   "X....   X        ",
			   "XXXXXXXXX        "};
	level[44]={"      XXXXXX             ",
			   "   XXXXX   X             ",
			   "   X   X X XXXXX         ",
			   "   X * X  *    XXXXXX    ",
			   "  XX*  XXX XX       X    ",
			   "XXX  ** * * X  XX   XXXXX",
			   "X       *   XXXXXX XX   X",
			   "X  XXXXXXXX X@   X X  X X",
			   "XX XXX      XXXX X*X X  X",
			   " X XXX XXXX XX.. X   * XX",
			   " X  *  *  X*XX.. X*XX  XX",
			   " X  X X X     ..XX XX * X",
			   " XXXX   X XX X..X    *  X",
			   "    XXXXX    X..X X X  XX",
			   "        XXXXXX..X   X XX ",
			   "             X..XXXXX  X ",
			   "             X..       X ",
			   "             XX  XXX  XX ",
			   "              XXXXXXXXX  "};
	level[45]={"        XXXXXXX    ",
			   "    XXXXX  X  XXXX ",
			   "    X   X   *    X ",
			   " XXXX X** XX XX  X ",
			   "XX      X X  XX XXX",
			   "X  XXX *X*  *  *  X",
			   "X...    X XX  X   X",
			   "X...X    @ X XXX XX",
			   "X...X  XXX  *  *  X",
			   "XXXXXXXX XX   X   X",
			   "          XXXXXXXXX"};
	level[46]={"    XXXXXXXXX  XXXX   ",
			   "    X   XX  XXXX  X   ",
			   "    X   *   X  *  X   ",
			   "    X  X XX X     XXXX",
			   "    XX *   * **X X   X",
			   "    XXXX  X  X * *   X",
			   "XXXXX  XXXX    XXX...X",
			   "X   X* X  X XXXX.....X",
			   "X      X  X X XX.....X",
			   "XXXXXX X  X*   XXX...X",
			   "   X   XX X *X   X...X",
			   "  XX       *  *X XXXXX",
			   " XX ***XX  X *   X    ",
			   " X   X  X XXX  XXX    ",
			   " X   *  X* @XXXX      ",
			   " XXXXX  X   X         ",
			   "     XXXXXXXX         "};
	level[47]={" XXXXX             ",
			   " X   X             ",
			   " X X XXXXXX        ",
			   " X      *@XXXXXX   ",
			   " X * XX* XXX   X   ",
			   " X XXXX *    * X   ",
			   " X XXXXX X  X* XXXX",
			   "XX  XXXX XX*      X",
			   "X  *X  *  X XX XX X",
			   "X         X X...X X",
			   "XXXXXX  XXX  ...  X",
			   "     XXXX X X...X X",
			   "          X XXX X X",
			   "          X       X",
			   "          XXXXXXXXX"};
	level[48]={"       XXXX     ",
			   "       X  XX    ",
			   "       X   XX   ",
			   "       X ** XX  ",
			   "     XXX*  * XX ",
			   "  XXXX    *   X ",
			   "XXX  X XXXXX  X ",
			   "X    X X....* X ",
			   "X X   * ....X X ",
			   "X  * X X.&..X X ",
			   "XXX  XXXX XXX X ",
			   "  XXXX @*  XX*XX",
			   "     XXX *     X",
			   "       X  XX   X",
			   "       XXXXXXXXX"};
	level[49]={"      XXXXXXXXXXXX ",
			   "     XX..    X   X ",
			   "    XX..& *    * X ",
			   "   XX..&.X X X* XX ",
			   "   X..&.X X X *  X ",
			   "XXXX...X  X    X X ",
			   "X  XX X          X ",
			   "X @* * XXX  X X XX ",
			   "X *   *   X X   X  ",
			   "XXX**   X X X X X  ",
			   "  X   *   X X XXXXX",
			   "  X *X XXXXX      X",
			   "  X*   X   X   X  X",
			   "  X  XXX   XX     X",
			   "  X  X      X    XX",
			   "  XXXX      XXXXXX "};
	level[50]={"     XXXXXXXXXXXXX   ",
			   "     X    XXX    X   ",
			   "     X     * *  XXXX ",
			   "   XXXX X   * *    X ",
			   "  XX *  X*XXXX * * X ",
			   "XXX   X X   XXX  * X ",
			   "X *  *  X  *  X XXXX ",
			   "X XX*XXXX X*X  *  XXX",
			   "X XX  XXX X X X  *  X",
			   "X    @*   *   X * X X",
			   "XXXXX  X  XX  X *X  X",
			   "  X... XXXXX*  X  X X",
			   "  X.......X ** X* X X",
			   "  X.......X         X",
			   "  X.......XXXXXXX  XX",
			   "  XXXXXXXXX     XXXX "};
	level[51]={"XXXXX XXXX      ",
			   "X...X X  XXXX   ",
			   "X...XXX  *  X   ",
			   "X....XX *  *XXX ",
			   "XX....XX   *  X ",
			   "XXX... XX * * X ",
			   "X XX    X  *  X ",
			   "X  XX X XXX XXXX",
			   "X * X X*  *    X",
			   "X  * @ *    *  X",
			   "X   X * ** * XXX",
			   "X  XXXXXX  XXX  ",
			   "X XX    XXXX    ",
			   "XXX             "};
	level[52]={" XXXX                ",
			   "XX  XXXXX            ",
			   "X       X XXXXX      ",
			   "X *XXX  XXX   X      ",
			   "X..X  *X X  X X      ",
			   "X..X      **X XXX    ",
			   "X.&X X  X* *    XXXXX",
			   "X..X  XX     XX*X   X",
			   "X.&*  * X XX  *     X",
			   "X..XX  *   X   XXXXXX",
			   "X.&XX*XX   XXXXX     ",
			   "X..  * XXXXX         ",
			   "X  X @ X             ",
			   "XXXXXXXX             "};
	level[53]={"   XXXXXXXXXX",
			   "   X  XXX   X",
			   "   X *   *  X",
			   "   X  XXXX*XX",
			   "   XX X  X  X",
			   "  XX  X.&   X",
			   "  X  XX..X  X",
			   "  X @ X.&X XX",
			   "  X X*X..X* X",
			   "  X * X..X  X",
			   "  X X X&&X  X",
			   "  X * X..X*XX",
			   "  X    .&X  X",
			   " XXX  X  X  X",
			   "XX    XXXX  X",
			   "X  XXXXXXX*XX",
			   "X *      *  X",
			   "X  XX   X   X",
			   "XXXXXXXXXXXXX"};
	level[54]={" XXXXXXXXXXXXXXXXXXXXX ",
			   " X   XX  X   X   X   X ",
			   " X *     *   *   *   XX",
			   "XXXXX X  X   XXX XX*XXX",
			   "X   X XX*XXXXXX   X   X",
			   "X *   X ......X   X * X",
			   "XX X  X ......XXXXX   X",
			   "XX XXXXXXXXX..X   X XXX",
			   "X          X..X *   X  ",
			   "X XX XXX XXX..XX X  XXX",
			   "X X   X   XX..XX XXX  X",
			   "X   @      *..X       X",
			   "X X   X   XX  X   XX  X",
			   "XXXXX XXXXXXXXXXXXXX XX",
			   "X          X   X    * X",
			   "X *  X * * *   X X    X",
			   "X X*XX *X  XX XX    X X",
			   "X  * ** XXXX *  * X X X",
			   "X          X   X      X",
			   "XXXXXXXXXXXXXXXXXXXXXXX"};
	level[55]={" XXXXXXXXXXXXXXXXXXXXX",
			   "XX                   X",
			   "X    * X      XX X   X",
			   "X  XXXXXX XXX  X*XX XX",
			   "XX*X   XX*X....   X X ",
			   "X  X    * X....XX X X ",
			   "X * X X X X....XX   X ",
			   "X * X**   X....XX*X X ",
			   "X X *@*XX*X....XX   X ",
			   "X   ***   X....X    X ",
			   "X  *X   X XXXXXX *XXX ",
			   "XX  X XXX**  *   * X  ",
			   "XX     X *  * XX   X  ",
			   " XXXXX   X   XXXXXXX  ",
			   "     XXXXXXXXX        "};
	level[56]={"XXXXXXXXXX    ",
			   "X        XXXX ",
			   "X XXXXXX X  XX",
			   "X X * * *  * X",
			   "X       X*   X",
			   "XXX*  **X  XXX",
			   "  X  XX X *XX ",
			   "  XX*X   * @X ",
			   "   X  * * XXX ",
			   "   X X   *  X ",
			   "   X XX   X X ",
			   "  XX  XXXXX X ",
			   "  X         X ",
			   "  X.......XXX ",
			   "  X.......X   ",
			   "  XXXXXXXXX   "};
	level[57]={"         XXXX     ",
			   " XXXXXXXXX  XX    ",
			   "XX  *      * XXXXX",
			   "X   XX XX   XX...X",
			   "X X** * **X*XX...X",
			   "X X    @  X   ...X",
			   "X  *X XXX**   ...X",
			   "X *  **  * XX....X",
			   "XXX*       XXXXXXX",
			   "  X  XXXXXXX      ",
			   "  XXXX            "};
	level[58]={"              XXXXXX       ",
			   "          XXXXX    X       ",
			   "          X  XX X  XXXXX   ",
			   "          X   &.X..X   X   ",
			   " XXXXX XXXX *X.X...    X   ",
			   " X   XXX  XX X&....XX XX   ",
			   " X *      XX X..X..XX X    ",
			   "XXXXXX X   X X&.XXXXX X    ",
			   "X   X *X*X X X..XXXXX X    ",
			   "X *  *     X X&.    X X    ",
			   "XX XX  * XXX X  XX  X X    ",
			   " X  *  * XXX XXXXX XX X    ",
			   " XXX*XXX*XXX  XXXX XX X    ",
			   "XXXX X         XXX  X X    ",
			   "X  * X  *XXXX  XXX**X@XXXXX",
			   "X      * X X  XXXX  X*X   X",
			   "XXXX X  *X X              X",
			   "   X  *  X XX  XX  XXXXXXXX",
			   "   XX  XXX  XXXXXXXX       ",
			   "    XXXX                   "};
	level[59]={"         XXXX                ",
			   "         X  X                ",
			   "         X  XXXXXXXX         ",
			   "   XXXXXXX  X      X         ",
			   "   X   X X X X X   XX        ",
			   "   X *     *  XX  * X        ",
			   "  XXX *X X  X X     XXXXXXXXX",
			   "  X  *  X  *X X ** X   X X  X",
			   " XX X   X     XXX    * X X  X",
			   " X  X*   X XXX  X  X **X X  X",
			   " X    *XX *  X   XX *  X X XX",
			   "XXXX* * X    XX  X   *    ..X",
			   "X  X    XXX X * * XXX  XXX.&X",
			   "X     XX  ** @  *     XX....X",
			   "X  XX  XX   *  X*X  XX....&.X",
			   "XX X  *  X X *XX  XX....&.XXX",
			   "XX XX  *  X * X  X....&.XXX  ",
			   "X    * XXXX   X ....&.XXX    ",
			   "X   X  X  X  X  ..&.XXX      ",
			   "XXXXXXXX  XXXXXXXXXXX        "};
	/*level[60]={"        XXXXX             ",
			   "        X   XXXX          ",
			   "        X *    XXXX  XXXX ",
			   "        X   X *X  XXXX  X ",
			   "XXXXXXXXXXX X   *   X   X ",
			   "X..     X *  XXXX X  X  X ",
			   "X..*  X   *  X  * X * .XX ",
			   "X.&X X * * XX  XX    X.X  ",
			   "X..X* @ X   XX    ** X.X  ",
			   "X..X * *  * * XX   XX .X  ",
			   "X.&** X XX   * X*X * X.X  ",
			   "X..X      XX   X     X.X  ",
			   "X..XXXXXXX  XXX XXXXXX.XX ",
			   "X **                  &.XX",
			   "X  XXXXXXXXXXXXXXXXXX  ..X",
			   "XXXX                XXXXXX"};
*/
}

void Levels::getLevel(vector<vector<Tile>> *tile, int levelnum){
	int sizeY = level[levelnum].size();
	int sizeX = level[levelnum][0].size();

	tile->reserve(sizeY);

	for(int i=0; i<sizeY; i++){
		vector<Tile> tileRow(sizeX);
		for(int j=0; j<sizeX; j++){
			if(level[levelnum][i][j]=='X')
				tileRow[j]=Wall;
			if(level[levelnum][i][j]==' ')
				tileRow[j]=Grass;
			if(level[levelnum][i][j]=='*')
				tileRow[j]=Box;
			if(level[levelnum][i][j]=='.')
				tileRow[j]=Exit;
			if(level[levelnum][i][j]=='&')
				tileRow[j]=ExitBox;
			if(level[levelnum][i][j]=='@') {
				tileRow[j]=GrassPlayer;
				//actor->put(j,i);
			}
		}
		tile->push_back(tileRow);
		tileRow.clear();
	}
	return;
}
